app = "chexs"
primary_region = "lax"

[env]
PORT = "8080"

[processes]
app = "run -A ./server.ts"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
