app = "chexs"
primary_region = "lax"

[env]
PORT = "8666"

[processes]
app = "run --allow-env --allow-net --allow-read ./server.ts"

[http_service]
internal_port = 8666
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
